### ISSUE TITLE
get_resolution broken in util.py

### ISSUE THREAD

**Issue by GloriousEggroll** [Open-Wine-Components/ULWGL-protonfixes#17]
```
ProtonFixes[382510] INFO: Running protonfixes
ProtonFixes[382510] INFO: Running checks
ProtonFixes[382510] INFO: All checks successful
ProtonFixes[382510] INFO: Using global defaults for "Gothic 1 Classic" (65540)
ProtonFixes[382510] INFO: Using protonfix for "Gothic 1 Classic" (65540)
ProtonFixes Traceback (most recent call last):
  File "/home/tcrider/.local/share/Steam/compatibilitytools.d/GE-Proton8-32/protonfixes/__init__.py", line 20, in <module>
    fix.main()
  File "/home/tcrider/.local/share/Steam/compatibilitytools.d/GE-Proton8-32/protonfixes/fix.py", line 201, in main
    run_fix(game_id())
  File "/home/tcrider/.local/share/Steam/compatibilitytools.d/GE-Proton8-32/protonfixes/fix.py", line 180, in run_fix
    game_module.main()
  File "/home/tcrider/.local/share/Steam/compatibilitytools.d/GE-Proton8-32/protonfixes/gamefixes-steam/65540.py", line 11, in main
    screen_width,screen_height = util.get_resolution()
  File "/home/tcrider/.local/share/Steam/compatibilitytools.d/GE-Proton8-32/protonfixes/util.py", line 582, in get_resolution
    with open('/sys/class/graphics/fb0/virtual_size', 'r') as res:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/graphics/fb0/virtual_size'
```

**Comment by GloriousEggroll** [comment]
https://unix.stackexchange.com/questions/768915/linux-6-7-sys-class-graphics-fb0-is-missing

**Comment by imLinguin** [comment]
So we need to switch to use DRM instead

**Comment by GloriousEggroll** [comment]
we can just add xrandr to protonfixes,  its way easier and I verified it works within the container
